### ISSUE TITLE
Отображает странные таймкоды без видимой причны

### ISSUE THREAD

**Issue by BostonSQ** [trippymajo/iEDeaL#3]
![Снимок экрана (156)](https://github.com/user-attachments/assets/e6d385bc-e1a3-4f22-ae7d-eee00a13f6b2)

**Comment by trippymajo** [comment]
It is a problem because of #2

> Fixed in [0c2d838](https://github.com/trippymajo/iEDeaL/commit/0c2d838d3e53a0bb17e55d157af041d6bfef65a9)
> v.1.1+
