### ISSUE TITLE
Отобржает То что на видео

### ISSUE THREAD

**Issue by BostonSQ** [trippymajo/iEDeaL#4]
Почему-то отображает рандомный слой который находится на видео дорожке, для которого звуковой дорожки не может быть
![Снимок экрана (157)](https://github.com/user-attachments/assets/8d5e15ce-9ef3-4769-aabe-b3bb95d9831d)

**Comment by trippymajo** [comment]
Fixed in [c7e777d](https://github.com/trippymajo/iEDeaL/commit/c7e777d4964a4acd5a821e0cf6271da702fe6beb)
v.1.1+
